# Generated by Django 3.2 on 2022-05-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Адрес')),
                ('lng', models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Широта')),
                ('lat', models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Долгота')),
                ('request_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['address'],
            },
        ),
    ]
