# Generated by Django 3.2 on 2022-04-27 09:57

from django.db import migrations

def fill_price_field_in_order_items(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.all().iterator(chunk_size=1000):
        product_price = item.product.price
        if not item.price:
            item.price = product_price
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(fill_price_field_in_order_items),
    ]
