# Generated by Django 3.2 on 2022-05-04 17:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 0, 35, 1, 513769), verbose_name='Дата звонка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 0, 35, 33, 626409), verbose_name='Дата доставки'),
            preserve_default=False,
        ),
    ]
