# Generated by Django 3.2 on 2022-05-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20220505_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creation_date',
            new_name='registration_date',
        ),
    ]
