# Generated by Django 3.2 on 2022-05-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_rename_creation_date_order_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CS', 'Налич.'), ('EL', 'Элект.')], db_index=True, default='CS', max_length=2, verbose_name='Способ оплаты'),
        ),
    ]
