# Generated by Django 3.2 on 2022-06-04 01:48

from django.db import migrations


def replace_blank_comment(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    for order in Order.objects.all():
        if order.comment == None:
            order.comment = ''
            order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RunPython(replace_blank_comment),
    ]
