# Generated by Django 3.2 on 2022-06-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_auto_20220605_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='cook_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cook_in', to='foodcartapp.restaurant', verbose_name='Приготовить в'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RW', 'Необработ.'), ('DR', 'Готовится'), ('PR', 'Обработ.')], db_index=True, default='RW', max_length=2, verbose_name='Статус'),
        ),
    ]
