# Generated by Django 3.2 on 2022-07-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0065_auto_20220625_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cook_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Приготовить в'),
        ),
    ]
